version: '3.5'
services:
  diary_db:
    container_name: 'diary_db'
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5445:5432'
